# Q1 Matrix formation of order 2*3 using for loop.

In [3]:
r=[]
for x in range(2):
    c=[]
    for y in range(3):
        c.insert(y,input())
    r.insert(x,c)
for z in r:
    print(z)
print("Order = 2 * 3 ")
print(r)

1
2
3
4
5
6
['1', '2', '3']
['4', '5', '6']
Order = 2 * 3 
[['1', '2', '3'], ['4', '5', '6']]


# Q2 Take value of no. of rows and column form user and create its dynamic size.

In [5]:
row=int(input("Enter no of row HERE= "))
col=int(input("Enter no of column HERE= "))
r=[]
for x in range(row):
    c=[]
    for y in range(col):
        c.insert(y,int(input()))
    r.insert(x,c)
for z in r:
    print(z)
print("Order = ",row,"*",col)
print(r)

Enter no of row HERE= 3
Enter no of column HERE= 3
1
2
3
4
5
6
7
8
91
[1, 2, 3]
[4, 5, 6]
[7, 8, 91]
Order =  3 * 3
[[1, 2, 3], [4, 5, 6], [7, 8, 91]]


# MATRIX FORMATION USING NUMPY

In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,0],[0,1]])
c=np.add(a,b)
print(c)

[[2 2]
 [3 5]]


In [20]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,0],[0,1]])
print("A=",a,"\nB=",b)
c=np.dot(a,b)
print("C=A*B")
print("C=",c)

A= [[1 2]
 [3 4]] 
B= [[1 0]
 [0 1]]
C=A*B
C= [[1 2]
 [3 4]]


In [24]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.linalg.inv(a)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [25]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.transpose(a)
print(b)

[[1 3]
 [2 4]]


In [26]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.linalg.det(a)
print(b)

-2.0000000000000004


In [29]:
import numpy as np
a=np.array([[1,2],[3,4]])
b,c=np.linalg.eig(a)
print("Eigen Value=",b,"\nEigen Vector=",c)

Eigen Value= [-0.37228132  5.37228132] 
Eigen Vector= [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Question - 7

In [40]:
import numpy as np
row=int(input("Enter no of row HERE= "))
col=int(input("Enter no of column HERE= "))
r=[]
for x in range(row):
    c=[]
    for y in range(col):
        c.insert(y,int(input("Enter no.= ")))
    r.insert(x,c)
a=np.array(r)
print(a)
x=[]
for z in range(row):
    x.append(int(input("Enter column vector no.= ")))
b=np.array(x)
b=b.reshape(row,1)
print(b)
c=np.dot(a,b)
print(c)
z=1
n=0
j=[]
i=np.array(j)
while(True==True):
    n=m
    j=i
    m=c.max()
    i=np.dot(c,1/m)
    print("No. of Iterations = ",z)
    print("Eigen Value = ",m)
    print("Eigen Vector = ",i)
    c=np.dot(a,i)
    z+=1
    m=round(m,3)
    n=round(n,3)
    if(m==n):
        print("Your largest Eigen value is \n",m,"\nAnd corresponding Eigen vector = \n",c)
        break

Enter no of row HERE= 4
Enter no of column HERE= 4
Enter no.= 0
Enter no.= 1
Enter no.= 1
Enter no.= 0
Enter no.= 0
Enter no.= 0
Enter no.= 1
Enter no.= 0
Enter no.= 0
Enter no.= 0
Enter no.= 0
Enter no.= 1
Enter no.= 1
Enter no.= 1
Enter no.= 0
Enter no.= 0
[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 1 0 0]]
Enter column vector no.= 1
Enter column vector no.= 1
Enter column vector no.= 1
Enter column vector no.= 1
[[1]
 [1]
 [1]
 [1]]
[[2]
 [1]
 [1]
 [2]]
No. of Iterations =  1
Eigen Value =  2
Eigen Vector =  [[1. ]
 [0.5]
 [0.5]
 [1. ]]
No. of Iterations =  2
Eigen Value =  1.5
Eigen Vector =  [[0.66666667]
 [0.33333333]
 [0.66666667]
 [1.        ]]
No. of Iterations =  3
Eigen Value =  1.0
Eigen Vector =  [[1.        ]
 [0.66666667]
 [1.        ]
 [1.        ]]
No. of Iterations =  4
Eigen Value =  1.6666666666666665
Eigen Vector =  [[1. ]
 [0.6]
 [0.6]
 [1. ]]
No. of Iterations =  5
Eigen Value =  1.6
Eigen Vector =  [[0.75 ]
 [0.375]
 [0.625]
 [1.   ]]
No. of Iterations =  6
Eigen Value

In [29]:
c=np.dot(a,b)
print(c)
z=0
j=[]
i=np.array(j)
while(True==True):
    n=m
    j=i
    m=c.max()
    i=np.dot(c,1/m)
    print("No. of Iterations = ",z+1)
    print("Eigen Value = ",m)
    print("Eigen Vector = ",i)
    c=np.dot(a,i)
    z+=1
    if(list(i)==list(j)):
        break

[[3]
 [7]]
No. of Iterations =  1
Eigen Value =  7
Eigen Vector =  [[0.42857143]
 [1.        ]]
No. of Iterations =  2
Eigen Value =  5.285714285714286
Eigen Vector =  [[0.45945946]
 [1.        ]]
No. of Iterations =  3
Eigen Value =  5.378378378378378
Eigen Vector =  [[0.45728643]
 [1.        ]]
No. of Iterations =  4
Eigen Value =  5.371859296482412
Eigen Vector =  [[0.45743686]
 [1.        ]]
No. of Iterations =  5
Eigen Value =  5.3723105706267535
Eigen Vector =  [[0.45742643]
 [1.        ]]
No. of Iterations =  6
Eigen Value =  5.372279296534912
Eigen Vector =  [[0.45742715]
 [1.        ]]
No. of Iterations =  7
Eigen Value =  5.372281463715036
Eigen Vector =  [[0.4574271]
 [1.       ]]
No. of Iterations =  8
Eigen Value =  5.37228131353657
Eigen Vector =  [[0.45742711]
 [1.        ]]
No. of Iterations =  9
Eigen Value =  5.37228132394344
Eigen Vector =  [[0.45742711]
 [1.        ]]
No. of Iterations =  10
Eigen Value =  5.372281323222278
Eigen Vector =  [[0.45742711]
 [1.        